#Если удалить этот файл, вам нужно будет будет:
#В файле by-name...
#1) Удалить строку 2 (from transcript import transcript) и 42 (		rurl = mrt.transcript(rurl)) (или поставить перед строкой '#')
#2) Предаётся вводить запрос транскрипцией.

def transcript(rurl):
	rurl = rurl.lower()
	rurl = rurl.replace(' ', '-')

##
#	rurl = rurl.replace('А', 'A')
#	rurl = rurl.replace('Б', 'B')
#	rurl = rurl.replace('В', 'V')
#	rurl = rurl.replace('Г', 'G')
#	rurl = rurl.replace('Д', 'D')
#	rurl = rurl.replace('Е', 'E')
#	rurl = rurl.replace('Ё', 'YO')
#	rurl = rurl.replace('Ж', 'ZH')
#	rurl = rurl.replace('З', 'Z')
#	rurl = rurl.replace('И', 'I')
#	rurl = rurl.replace('Й', 'J')
#	rurl = rurl.replace('К', 'K')
#	rurl = rurl.replace('Л', 'L')
#	rurl = rurl.replace('М', 'M')
#	rurl = rurl.replace('Н', 'N')
#	rurl = rurl.replace('О', 'O')
#	rurl = rurl.replace('П', 'P')
#	rurl = rurl.replace('Р', 'R')
#	rurl = rurl.replace('С', 'S')
#	rurl = rurl.replace('Т', 'T')
#	rurl = rurl.replace('У', 'U')
#	rurl = rurl.replace('Ф', 'F')
#	rurl = rurl.replace('Х', 'H')
#	rurl = rurl.replace('Ц', 'C')
#	rurl = rurl.replace('Ч', 'CH')
#	rurl = rurl.replace('Ш', 'SH')
#	rurl = rurl.replace('Щ', 'SHCH')
#	rurl = rurl.replace('Ъ', '')
#	rurl = rurl.replace('Ы', 'Y')
#	rurl = rurl.replace('Ь', '')
#	rurl = rurl.replace('Э', 'EH')
#	rurl = rurl.replace('Ю', 'YU')
#	rurl = rurl.replace('Я', 'YA')
##

#Буквы русского алфавита:
	rurl = rurl.replace('а', 'a')
	rurl = rurl.replace('б', 'b')
	rurl = rurl.replace('в', 'v')
	rurl = rurl.replace('г', 'g')
	rurl = rurl.replace('д', 'd')
	rurl = rurl.replace('е', 'e')
	rurl = rurl.replace('ё', 'yo')
	rurl = rurl.replace('ж', 'zh')
	rurl = rurl.replace('з', 'z')
	rurl = rurl.replace('и', 'i')
	rurl = rurl.replace('й', 'j')
	rurl = rurl.replace('к', 'k')
	rurl = rurl.replace('л', 'l')
	rurl = rurl.replace('м', 'm')
	rurl = rurl.replace('н', 'n')
	rurl = rurl.replace('о', 'o')
	rurl = rurl.replace('п', 'p')
	rurl = rurl.replace('р', 'r')
	rurl = rurl.replace('с', 's')
	rurl = rurl.replace('т', 't')
	rurl = rurl.replace('у', 'u')
	rurl = rurl.replace('ф', 'f')
	rurl = rurl.replace('х', 'h')
	rurl = rurl.replace('ц', 'c')
	rurl = rurl.replace('ч', 'ch')
	rurl = rurl.replace('ш', 'sh')
	rurl = rurl.replace('щ', 'shch')
	rurl = rurl.replace('ъ', '')
	rurl = rurl.replace('ы', 'y')
	rurl = rurl.replace('ь', '')
	rurl = rurl.replace('э', 'eh')
	rurl = rurl.replace('ю', 'yu')
	rurl = rurl.replace('я', 'ya')
	
#Символы:
	rurl = rurl.replace('!', '')
	rurl = rurl.replace('?', '')
	rurl = rurl.replace(',', '')
	rurl = rurl.replace('.', '')
	rurl = rurl.replace('*', '')
	rurl = rurl.replace('_', '')
	
	return rurl
